In [1]:
from pathlib import Path
import numpy as np

In [2]:
input = Path("example.txt").read_text()
EMPTY = "."
print(input)

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............



In [3]:
city = np.array([[value for value in line] for line in input.splitlines()])
city

array([['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '0', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '0', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '0', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '0', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', 'A', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', 'A', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', 'A', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']],
      dtype='<U1')

In [4]:
frequencies = np.unique(city)
frequencies = frequencies[frequencies != EMPTY]
frequencies

array(['0', 'A'], dtype='<U1')

In [5]:
antenna_locations = [np.argwhere(city == frequency) for frequency in frequencies]
antenna_locations

[array([[1, 8],
        [2, 5],
        [3, 7],
        [4, 4]], dtype=int64),
 array([[5, 6],
        [8, 8],
        [9, 9]], dtype=int64)]

In [6]:
all_antinodes = []
for antenna_location in antenna_locations:
    resonance = antenna_location[:, np.newaxis] - antenna_location
    antinodes = antenna_location - resonance
    # remove the orifinal location of the antenna from the antinodes
    antinodes = np.concatenate(
        [
            antinode[(antinode != original).all(axis=1)]
            for original, antinode in zip(antenna_location, antinodes)
        ]
    )
    all_antinodes.append(antinodes)
    antinodes.shape
all_antinodes = np.concatenate(all_antinodes)
all_antinodes

array([[ 3,  2],
       [ 5,  6],
       [ 7,  0],
       [ 0, 11],
       [ 4,  9],
       [ 6,  3],
       [-1,  9],
       [ 1,  3],
       [ 5,  1],
       [-2, 12],
       [ 0,  6],
       [ 2, 10],
       [11, 10],
       [13, 12],
       [ 2,  4],
       [10, 10],
       [ 1,  3],
       [ 7,  7]], dtype=int64)

In [7]:
unique_antinodes = np.unique(all_antinodes, axis=0)
unique_antinodes

array([[-2, 12],
       [-1,  9],
       [ 0,  6],
       [ 0, 11],
       [ 1,  3],
       [ 2,  4],
       [ 2, 10],
       [ 3,  2],
       [ 4,  9],
       [ 5,  1],
       [ 5,  6],
       [ 6,  3],
       [ 7,  0],
       [ 7,  7],
       [10, 10],
       [11, 10],
       [13, 12]], dtype=int64)

In [8]:
in_city = unique_antinodes[
    (unique_antinodes[:, 0] >= 0)
    & (unique_antinodes[:, 1] >= 0)
    & (unique_antinodes[:, 0] < city.shape[0])
    & (unique_antinodes[:, 1] < city.shape[1])
]
in_city

array([[ 0,  6],
       [ 0, 11],
       [ 1,  3],
       [ 2,  4],
       [ 2, 10],
       [ 3,  2],
       [ 4,  9],
       [ 5,  1],
       [ 5,  6],
       [ 6,  3],
       [ 7,  0],
       [ 7,  7],
       [10, 10],
       [11, 10]], dtype=int64)

In [9]:
in_city.shape[0]

14

In [10]:
# Solution 2
all_antinodes = []
for antenna_location in antenna_locations:
    resonance = antenna_location[:, np.newaxis] - antenna_location
    harmonics = np.arange(city.shape[0])[:, np.newaxis, np.newaxis, np.newaxis]
    antinodes = (antenna_location - resonance * harmonics).reshape(-1, 2)
    all_antinodes.append(antinodes)
all_antinodes = np.concatenate(all_antinodes)
unique_antinodes = np.unique(all_antinodes, axis=0)
in_city = unique_antinodes[
    (unique_antinodes[:, 0] >= 0)
    & (unique_antinodes[:, 1] >= 0)
    & (unique_antinodes[:, 0] < city.shape[0])
    & (unique_antinodes[:, 1] < city.shape[1])
]
in_city.shape[0]

34