In [6]:
from pathlib import Path

import numpy as np

In [7]:
input_data = Path("example.txt").read_text()
lines = input_data.splitlines()
coordinates = np.array([line.split(",") for line in lines], dtype=int)
coordinates

array([[ 7,  1],
       [11,  1],
       [11,  7],
       [ 9,  7],
       [ 9,  5],
       [ 2,  5],
       [ 2,  3],
       [ 7,  3]])

In [8]:
observations, dimensions = coordinates.shape
distances = np.zeros((observations, observations), dtype=int)


def compute_distance(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    return (np.abs(x - y) + 1).prod(axis=1)


for i in range(observations):
    distances[i] = compute_distance(coordinates, coordinates[i])

print(distances)

[[ 1  5 35 21 15 30 18  3]
 [ 5  1  7 21 15 50 30 15]
 [35  7  1  3  9 30 50 25]
 [21 21  3  1  3 24 40 15]
 [15 15  9  3  1  8 24  9]
 [30 50 30 24  8  1  3 18]
 [18 30 50 40 24  3  1  6]
 [ 3 15 25 15  9 18  6  1]]


In [9]:
print(distances.max())

50
