In [1]:
import numpy as np
from pathlib import Path

In [2]:
input = Path("example.txt").read_text()
print(input)

7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9



In [3]:
diff = [
    np.diff(np.array([int(value) for value in line.split()]))
    for line in input.splitlines()
]
diff

[array([-1, -2, -2, -1]),
 array([1, 5, 1, 1]),
 array([-2, -1, -4, -1]),
 array([ 2, -1,  2,  1]),
 array([-2, -2,  0, -3]),
 array([2, 3, 1, 2])]

In [4]:
# solution 1
is_safe = [
    ((row < 0).all() | (row > 0).all()) & (np.abs(row).max() <= 3) for row in diff
]
sum(is_safe)

2

In [5]:
# solution 2
safe_rows = []
for line in input.splitlines():
    diff = np.diff(np.array([int(value) for value in line.split()]))
    is_safe = ((diff < 0).all() | (diff > 0).all()) & (np.abs(diff).max() <= 3)
    if is_safe:
        safe_rows.append(is_safe)
        continue
    for i in range(len(line)):
        # leave out the ith value
        test = line.split()[:i] + line.split()[i + 1 :]
        diff = np.diff(np.array([int(value) for value in test]))
        is_safe = ((diff < 0).all() | (diff > 0).all()) & (np.abs(diff).max() <= 3)
        if is_safe:
            break
    safe_rows.append(is_safe)
sum(safe_rows)

4