In [151]:
from pathlib import Path

import numpy as np
import pandas as pd

In [152]:
input_data = Path("example.txt").read_text()
print(input_data)

123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  



## Part I

In [153]:
lines = input_data.splitlines()
values = np.array([line.split() for line in lines[:-1]], dtype=int)
print(values)

[[123 328  51  64]
 [ 45  64 387  23]
 [  6  98 215 314]]


In [154]:
operations = np.array(lines[-1].split(), dtype=str)
add_mask = np.where(operations == "+", 1, 0).astype(bool)

add = values.T[add_mask].sum(axis=1)
prod = values.T[~add_mask].prod(axis=1)

result = add.sum() + prod.sum()
print(result)

4277556


## Part II

In [155]:
values = [list(line) for line in lines[:-1]]
values = pd.DataFrame(values).sum().str.strip().add("   ").sum().split("    ")
max_len = max(len(v.split()) for v in values)
values = [
    [int(v) for v in value.split()] + [-1] * (max_len - len(value.split()))
    for value in values
    if value.strip()
]
values = np.array(values, dtype=int)
values = values.T
print(values)

[[  1 369  32 623]
 [ 24 248 581 431]
 [356   8 175   4]]


In [156]:
add = np.where(values > 0, values, 0).T[add_mask].sum(axis=1)
prod = np.where(values > 0, values, 1).T[~add_mask].prod(axis=1)

result = add.sum() + prod.sum()
print(result)

3263827
