# Advent of Code 2025, Day 3

In [123]:
from pathlib import Path

import numpy as np

In [124]:
input_path = Path("example.txt")
lines = input_path.read_text().strip().splitlines()
joltage = np.array([list(line) for line in lines], dtype=int)
print(joltage)

[[9 8 7 6 5 4 3 2 1 1 1 1 1 1 1]
 [8 1 1 1 1 1 1 1 1 1 1 1 1 1 9]
 [2 3 4 2 3 4 2 3 4 2 3 4 2 7 8]
 [8 1 8 1 8 1 9 1 1 1 1 2 1 1 1]]


In [125]:
CAPACITY = 12  # Part I: 2, Part II: 12

index = np.arange(joltage.shape[0], dtype=int)

# Initial highest rating index excluding leftmost CAPACITY-1 columns
rating_indices = [joltage[:, : -CAPACITY + 1].argmax(axis=1).astype(int)]

# Iterate to find next highest rating indices, starting from the last
# highest found and "unlocking" a column to the right
for i in range(1, CAPACITY):
    # Mask to exclude previously found highest ratings and columns to their left
    rating_mask = np.zeros_like(joltage, dtype=bool)
    mask_index = np.stack((index, rating_indices[i - 1]), axis=1)
    for j in range(len(index)):
        rating_mask[j, rating_indices[i - 1][j] + 1 :] = True
    masked_joltage = np.where(rating_mask, joltage, 0)

    # End is to exclude rightmost columns that cannot be considered yet
    end = -CAPACITY + 1 + i if i < CAPACITY - 1 else None
    rating_indices.append(masked_joltage[:, :end].argmax(axis=1))

# Find ratings from indices and combine into full battery ratings
ratings = []
for i in range(CAPACITY):
    rating = joltage[index, rating_indices[i]] * (10 ** (CAPACITY - 1 - i))
    ratings.append(rating)

result = np.sum(ratings)
print(result)


3121910778619
