In [41]:
import numpy as np
from pathlib import Path
from itertools import permutations

In [42]:
puzzle_input = Path("example.txt").read_text()
print(puzzle_input)

...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....



In [43]:
lines = puzzle_input.splitlines()
arr = np.array([list(line) for line in lines])
arr = np.where(arr == "#", 1, 0)
print(f"Shape: {arr.shape}")
print(arr)

Shape: (10, 10)
[[0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]]


In [44]:
empty_space = np.where(arr.sum(axis=0) == 0)[0], np.where(arr.sum(axis=1) == 0)[0]
print(empty_space[0], empty_space[1])

[2 5 8] [3 7]


In [45]:
y, x = np.where(arr == 1)
stars = np.array([[x, y] for x, y in zip(x, y)])
print(stars)

[[3 0]
 [7 1]
 [0 2]
 [6 4]
 [1 5]
 [9 6]
 [7 8]
 [0 9]
 [4 9]]


In [46]:
def dist(start, end, expansion=2):
    cross_x = (start[0] < empty_space[0]) & (end[0] > empty_space[0])
    cross_y = (start[1] < empty_space[1]) & (end[1] > empty_space[1])
    crosses = cross_x.sum() + cross_y.sum()
    empty_space_modifier = crosses * (expansion - 1)
    return np.abs(start - end) + empty_space_modifier

## Part I

In [47]:
np.array([dist(start, end) for start, end in permutations(stars, 2)]).sum() // 2

374

## Part II

In [48]:
np.array([dist(start, end, 10) for start, end in permutations(stars, 2)]).sum() // 2

1030

In [49]:
np.array([dist(start, end, 100) for start, end in permutations(stars, 2)]).sum() // 2

8410