In [1]:
from pathlib import Path

import networkx as nx
import numpy as np

In [2]:
input = Path("example.txt").read_text()
print(input)

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732



In [3]:
topo = np.array([[value for value in line] for line in input.splitlines()], dtype=int)
pad_topo = np.pad(topo, pad_width=1, constant_values=-2)
print(pad_topo)

[[-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-2  8  9  0  1  0  1  2  3 -2]
 [-2  7  8  1  2  1  8  7  4 -2]
 [-2  8  7  4  3  0  9  6  5 -2]
 [-2  9  6  5  4  9  8  7  4 -2]
 [-2  4  5  6  7  8  9  0  3 -2]
 [-2  3  2  0  1  9  0  1  2 -2]
 [-2  0  1  3  2  9  8  0  1 -2]
 [-2  1  0  4  5  6  7  3  2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]]


In [4]:
G = nx.DiGraph()

In [5]:
for axis in [0, 1]:
    for direction in [-1, 1]:
        has_edge = pad_topo - np.roll(pad_topo, direction, axis) == 1
        first_node = (
            np.argwhere(has_edge)
            - np.array([1 if axis == 0 else 0, 1 if axis == 1 else 0]) * direction
        )
        second_node = np.argwhere(has_edge)
        for first, second in zip(first_node, second_node):
            G.add_edge(tuple(first - 1), tuple(second - 1))
print("Number of Nodes:", len(G.nodes))
print("Number of Edges:", len(G.edges))

Number of Nodes: 64
Number of Edges: 73


In [6]:
starts = np.argwhere(topo == 0)
ends = np.argwhere(topo == 9)

In [7]:
# Solution 1
sum(
    [
        sum([nx.has_path(G, tuple(start), tuple(end)) for end in ends])
        for start in starts
    ]
)

36

In [8]:
# Solution 2
sum(
    [
        sum(
            [
                len(list(nx.all_simple_edge_paths(G, tuple(start), tuple(end))))
                for end in ends
            ]
        )
        for start in starts
    ]
)

81