In [1]:
from pathlib import Path
import re

import numpy as np

In [2]:
input = Path("example.txt").read_text()
print(input)

p=0,4 v=3,-3
p=6,3 v=-1,-3
p=10,3 v=-1,2
p=2,0 v=2,-1
p=0,0 v=1,3
p=3,0 v=-2,-2
p=7,6 v=-1,-3
p=3,0 v=-1,-2
p=9,3 v=2,3
p=7,3 v=-1,2
p=2,4 v=2,-3
p=9,5 v=-3,-3



In [3]:
# Example
dimensions = np.array([11, 7])
# Input
# dimensions = np.array([101, 103])

In [4]:
pattern = r"p=(\d+),(\d+) v=(-?\d+),(-?\d+)"
data = np.array(re.findall(pattern, input), dtype=np.int32)
data

array([[ 0,  4,  3, -3],
       [ 6,  3, -1, -3],
       [10,  3, -1,  2],
       [ 2,  0,  2, -1],
       [ 0,  0,  1,  3],
       [ 3,  0, -2, -2],
       [ 7,  6, -1, -3],
       [ 3,  0, -1, -2],
       [ 9,  3,  2,  3],
       [ 7,  3, -1,  2],
       [ 2,  4,  2, -3],
       [ 9,  5, -3, -3]])

In [5]:
data.shape

(12, 4)

In [6]:
initial_position = data[:, :2]
initial_position

array([[ 0,  4],
       [ 6,  3],
       [10,  3],
       [ 2,  0],
       [ 0,  0],
       [ 3,  0],
       [ 7,  6],
       [ 3,  0],
       [ 9,  3],
       [ 7,  3],
       [ 2,  4],
       [ 9,  5]])

In [7]:
velocity = data[:, 2:]
velocity

array([[ 3, -3],
       [-1, -3],
       [-1,  2],
       [ 2, -1],
       [ 1,  3],
       [-2, -2],
       [-1, -3],
       [-1, -2],
       [ 2,  3],
       [-1,  2],
       [ 2, -3],
       [-3, -3]])

In [8]:
time = 100
final_position = initial_position + velocity * time
final_position[:, 0] %= dimensions[0]
final_position[:, 1] %= dimensions[1]
final_position

array([[3, 5],
       [5, 4],
       [9, 0],
       [4, 5],
       [1, 6],
       [1, 3],
       [6, 0],
       [2, 3],
       [0, 2],
       [6, 0],
       [4, 5],
       [6, 6]])

In [9]:
median = dimensions // 2
print(median)

[5 3]


In [10]:
quadrant_i = np.all(final_position < median, axis=1)
quadrant_ii = (final_position[:, 0] > median[0]) & (final_position[:, 1] < median[1])
quadrant_iii = (final_position[:, 0] < median[0]) & (final_position[:, 1] > median[1])
quadrant_iv = np.all(final_position > median, axis=1)

np.prod(
    [
        np.sum(quadrant)
        for quadrant in [quadrant_i, quadrant_ii, quadrant_iii, quadrant_iv]
    ]
)

12

In [11]:
# Solution 1
min_var = np.infty
min_time = 0
for time in range(10000):
    final_position = initial_position + velocity * time
    final_position %= dimensions
    if np.var(final_position) < min_var:
        min_var = np.var(final_position)
        min_time = time
print(min_time, min_var)

12 4.331597222222222


In [12]:
np.set_printoptions(linewidth=300, edgeitems=100)

final_position = initial_position + velocity * min_time
final_position %= dimensions

canvas = np.full(dimensions, fill_value=" ")
for position in final_position:
    canvas[tuple(position)] = "X"
print("_" * dimensions[0])
for row in canvas.T:
    print("|" + "".join(row) + "|")
print("-" * dimensions[0])

___________
|           |
| X         |
|    XX     |
|   XX      |
|XXX   X    |
|      X    |
|      X  X |
-----------
