In [54]:
from itertools import product
from pathlib import Path

import numpy as np

In [55]:
input_data = Path("example.txt")
lines = input_data.read_text().strip().splitlines()

paper_roll_map = {".": 0, "@": 1, "x": 2}
THRESHOLD = 4

paper_rolls = np.array(
    [[paper_roll_map[char] for char in line] for line in lines],
)
pad_paper_rolls = np.pad(
    paper_rolls,
    pad_width=1,
    mode="constant",
    constant_values=0,
)
pad_mask = np.zeros_like(pad_paper_rolls, dtype=bool)
roll_mask = pad_paper_rolls > 0
pad_mask[0, :] = True
pad_mask[-1, :] = True
pad_mask[:, 0] = True
pad_mask[:, -1] = True

print(pad_paper_rolls)

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 1 1 0 0]
 [0 1 1 1 0 1 0 1 0 1 1 0]
 [0 1 1 1 1 1 0 1 0 1 1 0]
 [0 1 0 1 1 1 1 0 0 1 0 0]
 [0 1 1 0 1 1 1 1 0 1 1 0]
 [0 0 1 1 1 1 1 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 1 1 1 0]
 [0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 1 0 0]
 [0 1 0 1 0 1 1 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [56]:
shifts = product([-1, 0, 1], repeat=2)
shifts = [s for s in shifts if s != (0, 0)]

shifted_rolls = [
    np.roll(pad_paper_rolls, shift, axis=(0, 1)) for shift in shifts
]

adjacent = sum(shifted_rolls)
liftable = adjacent < THRESHOLD * roll_mask

# Part I
print(liftable.sum())

13


In [57]:
total = liftable.sum()
iteration = 0
while liftable.sum() > 0:
    iteration += 1
    pad_paper_rolls = np.where(liftable, 0, pad_paper_rolls)
    roll_mask = pad_paper_rolls > 0

    shifted_rolls = [
        np.roll(pad_paper_rolls, shift, axis=(0, 1)) for shift in shifts
    ]
    adjacent = sum(shifted_rolls)
    liftable = adjacent < THRESHOLD * roll_mask
    total += liftable.sum()
    if iteration > 1000:
        break


# Part II
print(total)

43
